services:
  - type: web
    name: family-feud-socket-server
    env: node
    buildCommand: npm install
    startCommand: npm run server
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
